# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/three-color-sun" # the subpath of your site, e.g. /blog
url: "http://www.menzenski.com" # the base hostname & protocol for your site

# Author settings
author:
    name: Firstname Lastname
    email: your-email@domain.com
    github: username
    twitter: username



# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
sass:
    sass_dir: _sass/


# Page/frontmatter settings
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            color_scheme: "light"
